import turtle
s=turtle.Screen()
s.bgcolor("light blue")
w = turtle.Turtle()
w.pencolor("black")
w.fillcolor("red")
w.penup()
w.goto(-200,50)
w.pendown()
w.begin_fill()
#To draw a square
for i in range(4):
 w.forward(100)
 w.left(90)
w.end_fill()
# To draw rectangle
w.penup()
w.goto(200,50)
w.pendown()
w.fillcolor("green")
w.begin_fill()
w.forward(100)
w.left(90)
w.forward(200)
w.left(90)
w.forward(100)
w.left(90)
w.forward(200)
w.left(90)
w.end_fill()
w.hideturtle()
