import turtle
f=open("tb_info.txt",'r')
content = f.readline()
agent=content.split()
agent_number=agent[2]
f.close()
print(agent_number)
screen = turtle.Screen()
t = turtle.Turtle()
t.speed(10)
def top():
 t.fillcolor("grey")
 t.penup()
 t.goto(-650,330)
 t.pendown()
 for i in range(2):
  t.begin_fill()
  t.forward(1300)
  t.right(90)
  t.forward(480)
  t.right(90)
  t.end_fill()
 t.penup()
 t.goto(-630,310)
 t.pendown()
 t.write("top",align="center",font=10)
 t.hideturtle()
def test():
 t.fillcolor("light blue")
 t.penup()
 t.goto(-630,300)
 t.pendown()
 for i in range(2):
  t.begin_fill()
  t.forward(1260)
  t.right(90)
  t.forward(420)
  t.right(90)
  t.end_fill()
 t.penup()
 t.goto(-600,280)
 t.pendown()
 t.write("test",align="center",font=10)
 #t.hideturtle()
def env():
 t.fillcolor("light green")
 t.penup()
 t.goto(-600,270)
 t.pendown()
 for i in range(2):
  t.begin_fill()
  t.forward(1200)
  t.right(90)
  t.forward(360)
  t.right(90)
  t.end_fill()
 t.penup()
 t.goto(-580,250)
 t.pendown()
 t.write("env",align="center",font=10)
 scoreboard()
 for i in range(int(agent_number)):
  agent(i)
  sequencer(i)
  driver(i)
  monitor(i)
  virtual_interface(i)
def scoreboard():
 t.fillcolor("light yellow")
 t.penup()
 t.goto(-280,240)
 t.pendown()
 for i in range(2):
  t.begin_fill()
  t.forward(570)
  t.right(90)
  t.forward(50)
  t.right(90)
  t.end_fill()
 t.penup()
 t.goto(-10,205)
 t.pendown()
 t.write("Scoreboard",align="center",font=12)
def agent(y):
 t.fillcolor("pink")
 t.penup()
 print(y,int(agent_number))
 x = y * ((1120/int(agent_number)) + 10)
 t.goto(-560 + x,180)
 t.pendown()
 for i in range(2):
  t.begin_fill()
  t.forward(1120/int(agent_number))
  t.right(90)
  t.forward(250)
  t.right(90)
  t.end_fill()
 t.penup()
 t.goto(-500 + x,120)
 t.pendown()
 t.write("Agent"+ str(y+1),align="center",font=10)
def sequencer(y):
 t.penup()
 print(y,int(agent_number))
 x = y * ((1120/int(agent_number)) + 10)
 t.goto(-550 + x,100)
 t.pendown()
 for i in range(2):
  t.forward(260/int(agent_number))
  t.right(90)
  t.forward(80)
  t.right(90)
 t.penup()
 t.goto((-545 + 130/int(agent_number))+ x,60)
 t.pendown()
 t.write("Sequencer",align="center",font=10)
 t.penup()
 t.goto(-550 + x + (260/int(agent_number)) ,60)
 t.pendown()
 z = (300/int(agent_number)) + 10
 t.goto((-540 + z + x),60)
 t.left(45)
 t.backward(10)
 t.forward(10)
 t.right(90)
 t.backward(10)
 t.forward(10)
 t.left(45)
def driver(y):
 t.penup()
 print(y,int(agent_number))
 x = y * ((1120/int(agent_number)) + 10)
 z = (300/int(agent_number)) + 10
 t.goto((-540 + z + x),100)
 t.pendown()
 for i in range(2):
  t.forward(300/int(agent_number))
  t.right(90)
  t.forward(80)
  t.right(90)
 t.penup()
 t.goto(-540 + z + x + 150/int(agent_number),60)
 t.pendown()
 t.write("Driver",align="center",font=10)
 t.penup()
 t.goto(-540 + z + x + 150/int(agent_number),20)
 t.pendown()
 t.right(90)
 t.pendown()
 t.forward(30)
 t.left(45)
 t.backward(10)
 t.forward(10)
 t.right(90)
 t.backward(10)
 t.forward(10)
 t.left(45)
 t.left(90)
def monitor(y):
 t.penup()
 print(y,int(agent_number))
 x = y * ((1120/int(agent_number)) + 10)
 z= 2 * (300/int(agent_number)) + 20
 t.goto((-540 + z + x),100)
 t.pendown()
 for i in range(2):
  t.forward(300/int(agent_number))
  t.right(90)
  t.forward(80)
  t.right(90)
 t.penup()
 t.goto(-540 + z + x + 150/int(agent_number),60)
 t.pendown()
 t.write("Monitor",align="center",font=10)
 t.penup()
 t.goto(-540 + z + x + 150/int(agent_number),-60)
 t.pendown()
 t.right(90)
 t.pendown()
 t.forward(70)
 t.backward(70)
 t.left(180)
 t.left(45)
 t.backward(10)
 t.forward(10)
 t.right(90)
 t.backward(10)
 t.forward(10)
 t.left(45)
 t.right(90)
def virtual_interface(y):
 t.penup()
 print(y, int(agent_number))
 x = y * ((1120 / int(agent_number)) + 10)
 z = (300 / int(agent_number)) + 10
 t.goto((-540 + z + x),-10)
 t.pendown()
 for i in range(2):
  t.forward(600 / int(agent_number))
  t.right(90)
  t.forward(50)
  t.right(90)
 t.penup()
 t.goto(-540 + z + x + 280 / int(agent_number), -50)
 t.pendown()
 t.write("Virtual Interface", align="center", font=10)
 t.penup()
 t.goto(-540 + z + x + 150 / int(agent_number), -60)
 t.pendown()
 t.right(90)
 t.pendown()
 t.forward(70)
 t.left(45)
 t.backward(10)
 t.forward(10)
 t.right(90)
 t.backward(10)
 t.forward(10)
 t.left(45)
 t.left(90)
 t.penup()
 x = y * ((1120 / int(agent_number)) + 10)
 z = 2 * (300 / int(agent_number)) + 20
 t.goto(-540 + z + x + 150 / int(agent_number), 20)
 t.pendown()
 t.right(90)
 t.pendown()
 t.forward(30)
 t.backward(30)
 t.left(180)
 t.left(45)
 t.backward(10)
 t.forward(10)
 t.right(90)
 t.backward(10)
 t.forward(10)
 t.left(45)
 t.right(90)

top()
test()
env()
